"""
Batch pre-compute — walk the 20 communities, build a full per-community
brief for each, and write data/briefs.json. This file is the single source
of truth the React frontend reads via /briefs.

Two modes:

  * default (LLM-backed): the three deterministic Python tools run
    in-process, then Grant Finder and Brief Writer are called over HTTPS
    against watsonx Orchestrate. Requires .env credentials and the seven
    agents registered in Orchestrate. (LLM mode is still stubbed — see
    NotImplementedError below — wire to Orchestrate's REST URL pattern
    once your instance is configured.)

  * --no-llm: deterministic Python fallback. Grant Finder uses rule-based
    eligibility matching; Brief Writer uses a string template that
    substitutes the computed values. Zero LLM calls, zero network. This
    is what unblocks the frontend build before Orchestrate is wired, AND
    serves as the safety-net path if Orchestrate is flaky on demo morning.

/* USAGE:
    # Deterministic fallback batch (no LLM, no network):
    python scripts/run_batch.py --no-llm

    # LLM-backed batch (once Orchestrate is wired):
    python scripts/run_batch.py

    # Limit to one community for debugging:
    python scripts/run_batch.py --only nain --no-llm --verbose

    # Custom output path:
    python scripts/run_batch.py --no-llm --output data/briefs_test.json
*/
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from api import economics, design, resource
from api.resource import get_community_record, list_community_ids
from api.schemas import (
    EligibleProgram,
    FundingMatch,
    RankingInputs,
    ValidationInfo,
)

BRIEFS_PATH_DEFAULT = ROOT / "data" / "briefs.json"

EQUITY_MULTIPLIER_INDIGENOUS = 1.5
EQUITY_MULTIPLIER_DEFAULT = 1.0


# ── Fallback Grant Finder ───────────────────────────────────────────────────

def _is_labrador(region: str) -> bool:
    r = region.lower()
    return "labrador" in r or "nunatsiavut" in r


def fallback_grant_finder(community: dict, econ_dict: dict) -> FundingMatch:
    """Rule-based eligibility — mirrors the hard rules in grant_finder.md."""
    is_indigenous = bool(community.get("indigenous"))
    is_labrador = _is_labrador(community["region"])
    capital_point = int(econ_dict["capital_cost_cad"]["point"])

    eligible: list[EligibleProgram] = []

    if is_labrador and is_indigenous:
        eligible.append(
            EligibleProgram(
                name="Reducing Diesel Dependency in Isolated Labrador Communities",
                max_cad=min(25_000_000, capital_point),
                eligibility_reasoning=(
                    "Indigenous-governed community in Labrador; eligible under "
                    "the program's geographic and Indigenous-priority criteria."
                ),
            )
        )

    if is_indigenous:
        eligible.append(
            EligibleProgram(
                name="Indigenous Off-Diesel Initiative",
                max_cad=min(15_000_000, capital_point),
                eligibility_reasoning=(
                    "Indigenous off-grid community pursuing community-led "
                    "clean energy; aligns with IODI scope."
                ),
            )
        )

    eligible.append(
        EligibleProgram(
            name="Clean Energy for Rural and Remote Communities",
            max_cad=min(15_000_000, capital_point),
            eligibility_reasoning=(
                "Off-grid diesel-dependent community; eligible under CERRC's "
                "national rural/remote scope."
            ),
        )
    )

    if capital_point >= 5_000_000:
        eligible.append(
            EligibleProgram(
                name="Smart Renewables and Electrification Pathways",
                max_cad=min(20_000_000, capital_point // 2),
                eligibility_reasoning=(
                    "Capital cost exceeds $5M; project scale qualifies under "
                    "SREP utility-scale criteria, especially as part of a "
                    "regional procurement bundle."
                ),
            )
        )

    potential_coverage = min(sum(p.max_cad for p in eligible), capital_point)

    return FundingMatch(
        eligible_programs=eligible,
        potential_coverage_cad=potential_coverage,
        notes=(
            "Generated by Python fallback rules. Replace with LLM Grant Finder "
            "once Orchestrate is wired."
        ),
    )


# ── Fallback Brief Writer ───────────────────────────────────────────────────

BRIEF_TEMPLATE = """## {name} — Off-Diesel Pre-Feasibility Brief

**Community:** {name}
**Region:** {region}
**Governance:** {governance}
**Current diesel load:** ~{load_kw:,} kW average, ~{annual_diesel_mil:.2f} M litres / year

## Executive Summary

A **{mix_label}** system is the lowest-cost path to reduce {name}'s diesel reliance. Estimated capital cost is **${cap_point_mil:.1f} M** (range ${cap_low_mil:.1f} M – ${cap_high_mil:.1f} M). The system would displace approximately **{fuel_saved_mil:.2f} million litres of diesel per year**, saving **${cost_saved_mil:.1f} M annually** and avoiding **{co2_t:,} tonnes of CO2**. Simple payback (excluding O&M): **{payback_yrs} years**. Federal funding from {primary_program} could cover up to **${primary_max_mil:.1f} M** of the capital cost.

## Resource Snapshot

Wind speed at 80 m: **{wind_mps} m/s** ({wind_quality} resource). Solar GHI: **{solar_ghi} kWh/m²/day** ({solar_quality} resource). Data sources: Global Wind Atlas (wind), NASA POWER (solar).

## Proposed System

| Component | Capacity range |
|---|---|
| Wind | {wind_kw_low:,} – {wind_kw_high:,} kW |
| Solar | {solar_kw_low:,} – {solar_kw_high:,} kW |
| Battery | {batt_kwh_low:,} – {batt_kwh_high:,} kWh |
| Retained diesel | {retained_diesel_kw:,} kW |

{sizing_rationale}

## Economics

| Metric | Value |
|---|---|
| Capital cost (low / point / high) | ${cap_low_mil:.1f} M / **${cap_point_mil:.1f} M** / ${cap_high_mil:.1f} M |
| Annual fuel saved | {fuel_saved_litres:,} litres |
| Annual cost saved | ${cost_saved_mil:.1f} M |
| Annual CO2 avoided | {co2_t:,} tonnes |
| Simple payback | {payback_yrs} years |

Simple payback excludes ongoing operations and maintenance. Real-world payback typically extends a few years longer once O&M is accounted for.

## Funding Match

{funding_block}

**Total indicative federal coverage: ${coverage_mil:.1f} M**

## Validation / Next Steps

{validation_text}
"""

FUNDING_LINE = "- **{name}** — indicative coverage up to **${max_mil:.1f} M**. {reason}"


def _quality(wind_mps: float, solar_ghi: float) -> tuple[str, str]:
    wq = "strong" if wind_mps >= 7 else "moderate" if wind_mps >= 5 else "weak"
    sq = "strong" if solar_ghi >= 4 else "moderate" if solar_ghi >= 3.5 else "weak"
    return wq, sq


def fallback_brief_writer(
    community: dict,
    rd,
    sizing,
    econ,
    funding: FundingMatch,
    validation: ValidationInfo,
) -> str:
    primary = funding.eligible_programs[0] if funding.eligible_programs else None
    funding_lines = [
        FUNDING_LINE.format(
            name=p.name,
            max_mil=p.max_cad / 1e6,
            reason=p.eligibility_reasoning,
        )
        for p in funding.eligible_programs
    ]
    funding_block = "\n".join(funding_lines) if funding_lines else "_No eligible programs matched._"

    if validation.real_project_exists:
        validation_text = (
            f"{validation.real_project_summary} "
            f"Meridian's recommendation matches the qualitative technology mix "
            f"of the project currently under construction."
        )
    else:
        validation_text = (
            "Preliminary recommendation. Requires confirmation against the "
            "community's actual load profile, site survey data, and "
            "consultation with the relevant governance body before any "
            "design or procurement step."
        )

    wq, sq = _quality(rd.wind_speed_80m_mps, rd.solar_ghi_kwh_m2_day)

    return BRIEF_TEMPLATE.format(
        name=community["name"],
        region=community["region"],
        governance=community["governance"],
        load_kw=community["current_diesel_kw_avg"],
        annual_diesel_mil=community["annual_diesel_litres"] / 1e6,
        mix_label=sizing.mix_label,
        cap_point_mil=econ.capital_cost_cad.point / 1e6,
        cap_low_mil=econ.capital_cost_cad.low / 1e6,
        cap_high_mil=econ.capital_cost_cad.high / 1e6,
        fuel_saved_mil=econ.annual_fuel_saved_litres / 1e6,
        fuel_saved_litres=econ.annual_fuel_saved_litres,
        cost_saved_mil=econ.annual_cost_saved_cad / 1e6,
        co2_t=econ.annual_co2_avoided_tonnes,
        payback_yrs=econ.payback_years,
        primary_program=primary.name if primary else "available programs",
        primary_max_mil=(primary.max_cad / 1e6) if primary else 0,
        wind_mps=rd.wind_speed_80m_mps,
        solar_ghi=rd.solar_ghi_kwh_m2_day,
        wind_quality=wq,
        solar_quality=sq,
        wind_kw_low=sizing.wind_kw.low,
        wind_kw_high=sizing.wind_kw.high,
        solar_kw_low=sizing.solar_kw.low,
        solar_kw_high=sizing.solar_kw.high,
        batt_kwh_low=sizing.battery_kwh.low,
        batt_kwh_high=sizing.battery_kwh.high,
        retained_diesel_kw=sizing.retained_diesel_kw,
        sizing_rationale=sizing.sizing_rationale,
        funding_block=funding_block,
        coverage_mil=funding.potential_coverage_cad / 1e6,
        validation_text=validation_text,
    )


# ── Validation block ────────────────────────────────────────────────────────

def build_validation(community: dict) -> ValidationInfo:
    status = (community.get("real_project_status") or "").strip()
    has_real_project = bool(status) and "no active" not in status.lower() and "none" not in status.lower()
    return ValidationInfo(
        real_project_exists=has_real_project,
        qualitative_match=has_real_project,
        real_project_summary=status or "No active off-diesel project announced.",
    )


# ── Orchestrate REST stubs (wire when your instance is ready) ───────────────

def llm_grant_finder(community: dict, econ_dict: dict) -> FundingMatch:
    """
    TODO: implement REST call to the meridian_grant_finder agent in
    watsonx Orchestrate. The exact URL pattern depends on your Orchestrate
    deployment; once confirmed, POST { community, economics } and parse the
    returned JSON into a FundingMatch.

    For now, this function raises so accidental LLM-mode runs fail loudly.
    """
    raise NotImplementedError(
        "LLM Grant Finder not yet wired to Orchestrate. "
        "Pass --no-llm to use the deterministic fallback."
    )


def llm_brief_writer(community, rd, sizing, econ, funding, validation) -> str:
    """TODO: implement REST call to meridian_brief_writer. See llm_grant_finder."""
    raise NotImplementedError(
        "LLM Brief Writer not yet wired to Orchestrate. "
        "Pass --no-llm to use the deterministic fallback."
    )


# ── Brief assembly ──────────────────────────────────────────────────────────

def build_brief(community_id: str, *, use_llm: bool, verbose: bool = False) -> dict:
    record = get_community_record(community_id)
    if verbose:
        print(f"  ▸ {record['name']:25s} ({community_id})")

    rd = resource.get_resource_data(community_id)
    sizing = design.size_system(community_id)
    econ = economics.compute_economics(community_id, sizing.model_dump())

    validation = build_validation(record)
    econ_dict = econ.model_dump()

    if use_llm:
        funding = llm_grant_finder(record, econ_dict)
        brief_md = llm_brief_writer(record, rd, sizing, econ, funding, validation)
    else:
        funding = fallback_grant_finder(record, econ_dict)
        brief_md = fallback_brief_writer(record, rd, sizing, econ, funding, validation)

    capital_point = econ.capital_cost_cad.point
    ranking_inputs = RankingInputs(
        dollar_per_dollar=round(econ.annual_cost_saved_cad / capital_point, 6),
        co2_per_dollar_kg=round((econ.annual_co2_avoided_tonnes * 1000) / capital_point, 6),
        equity_multiplier=(
            EQUITY_MULTIPLIER_INDIGENOUS if record.get("indigenous") else EQUITY_MULTIPLIER_DEFAULT
        ),
    )

    return {
        "id": record["id"],
        "name": record["name"],
        "lat": record["lat"],
        "lon": record["lon"],
        "depth": record.get("depth", "light"),
        "region": record["region"],
        "indigenous": bool(record.get("indigenous")),
        "resource": rd.model_dump(),
        "system": sizing.model_dump(),
        "economics": econ.model_dump(),
        "funding": funding.model_dump(),
        "validation": validation.model_dump(),
        "ranking_inputs": ranking_inputs.model_dump(),
        "brief_markdown": brief_md,
    }


# ── CLI ─────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Pre-compute Meridian briefs for the 20 NL diesel-dependent "
            "communities. Default mode calls Orchestrate; --no-llm uses the "
            "deterministic Python fallback."
        )
    )
    parser.add_argument(
        "--no-llm",
        action="store_true",
        help="Use deterministic fallback for Grant Finder and Brief Writer (no LLM, no network).",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Per-community progress.")
    parser.add_argument("--only", help="Process only this community id.")
    parser.add_argument(
        "--output",
        default=str(BRIEFS_PATH_DEFAULT),
        help=f"Output path (default: {BRIEFS_PATH_DEFAULT.relative_to(ROOT)})",
    )
    args = parser.parse_args()

    use_llm = not args.no_llm
    community_ids = [args.only] if args.only else list_community_ids()

    mode = "LLM (Orchestrate)" if use_llm else "fallback (deterministic)"
    word = "community" if len(community_ids) == 1 else "communities"
    print(f"Pre-computing briefs for {len(community_ids)} {word} — {mode} mode\n")

    briefs = []
    for cid in community_ids:
        try:
            briefs.append(build_brief(cid, use_llm=use_llm, verbose=args.verbose))
        except NotImplementedError as e:
            print(f"\n✗ {cid}: {e}", file=sys.stderr)
            return 2
        except Exception as e:
            print(f"\n✗ {cid}: {type(e).__name__}: {e}", file=sys.stderr)
            return 1

    output = {
        "metadata": {
            "schema_version": "1.0",
            "generation_mode": "llm" if use_llm else "fallback",
            "communities_total": len(briefs),
        },
        "communities": briefs,
    }

    out_path = Path(args.output)
    out_path.write_text(json.dumps(output, indent=2))
    print(f"\nWrote {len(briefs)} briefs → {out_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
